version: "3.2"
services: 
  frontend:
    restart: always
    command: npm start
    env_file: ./frontend/.env
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    stdin_open: true
